### ISSUE TITLE
Memory leak of file paths

### ISSUE THREAD

**Issue by ioannis-e** [meganz/MEGAsync#341]
There seems to be a memory leak at line 40 leaking the ``request`` string.
Can someone confirm and if possible fix.
Thank you.

https://github.com/meganz/MEGAsync/blob/22a1c064a73a927a42b31c4b26a542483e6742fe/src/MEGAShellExt/MEGAinterface.cpp#L36-L49

**Comment by polmr** [comment]
it seems so, this should fix it: https://github.com/meganz/desktop/pull/582

**Comment by ioannis-e** [comment]
Thank you @polmr.
Hmm, I cant follow the link provided.
Can you please advise whether the fix will be included in the next release and approximately when this will take place.
Thank you.

**Comment by polmr** [comment]
^^ wrong link, sorry. a
```
delete request;
```
after sendRequest should fix that. The latest version available to download from https://mega.nz/sync (4.2.3) won't include that yet. But I'm confident the next one will. No scheduled date yet.

**Comment by ioannis-e** [comment]
@polmr, just a quick reminder to ensure this doesn't go overlooked, this is still not resolved in v4.2.4
