### ISSUE TITLE
Error "megasync: error while loading shared libraries: libicuuc.so.74: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by ReinerSanders** [meganz/MEGAsync#951]
I am trying to reach someone from Mega, because the company's technical support really does not helps. They only told us to capture screenshots, and bla, bla, bla. Things we can do IF we can open the desktop app, whith I don't get anymore.

I am a PRO user, and I can't run Mega's desktop app anymore on Linux (EndeavourOS). If I try to open it through terminal, I always receive the below error:

`megasync: error while loading shared libraries: libicuuc.so.74: cannot open shared object file: No such file or directory`

I have already installed the app over my current installation, without success. Last time I had problems with Mega, I received no help. They only promised the devs would take care the issue and NOBODY answered me anymore. I had again to upload around 200 GB of data!

Someone know what can I do in order to solve this issue, please?

Thanks in advance.

**Comment by simonwiles** [comment]
This just happened to me a couple of minutes ago too.  `libicu` has been upgraded from 74 to 75, that's all.  The AUR has an `icu74` package that should solve the problem, but that's not building properly right now (someone needs to update the hash), so I just did a clean build of the `megasync` package and everything's fine (if you're using `megasync-bin` obviously you'll need to switch to `megasync`).

**Comment by simonwiles** [comment]
Duplicate of https://github.com/meganz/MEGAsync/issues/950.

**Comment by ReinerSanders** [comment]
How did you solve this, please?

Because here even `megasync` from AUR did not solve the issue, unfortunately.

**Comment by Ofthemasses** [comment]
> This just happened to me a couple of minutes ago too. `libicu` has been upgraded from 74 to 75, that's all. The AUR has an `icu74` package that should solve the problem, but that's not building properly right now (someone needs to update the hash), so I just did a clean build of the `megasync` package and everything's fine (if you're using `megasync-bin` obviously you'll need to switch to `megasync`).

Had the same problem with my `php-intl` install. `icu74` seems to build fine now using yay, solved my issues.

**Comment by Danielgb23** [comment]
Can you tell when magasync-bin will be fixed? I don't mind waiting if it's not too long

**Comment by blurrred** [comment]
Having the same issue, quality of megasync is dropping and I'm considering switching to a different backup tool.

**Comment by ReinerSanders** [comment]
I can only agree. Mega's technical support has been awful lately. I also have issue not solved, and they simply forgot about.

The "technicians" seems to be some kind of strange robots, moreover, and even refuse to let us know their names. They ask us to call them only as "Support Agent". This would be OK, of course, if at least they were be able to help us.

**Comment by vtmateos** [comment]
Dear users,
A new update for ARCH has been pushed in order to fix these issues. Please update and let us know if there is any other problem. Thanks.

**Comment by nkia-christoph** [comment]
> Dear users, A new update for ARCH has been pushed in order to fix these issues. Please update and let us know if there is any other problem. Thanks.

I had to manually install the icu74 aur package to get it to build.

**Comment by ReinerSanders** [comment]
Mega is constantly messing things. Today's updated messed everything here regarding backups, and that "screen for syncing problem solving" screen does nothing useful!

Going to search for another cloud backup provider asap!

**Comment by rautamiekka** [comment]
> Mega is constantly messing things. Today's update messed everything here regarding backups, and that "screen for syncing problem solving" does nothing useful!
> 
> Going to search for another cloud backup provider asap!

Goodluck with that, especially on Linux.

**Comment by ReinerSanders** [comment]
Yes, I know. And now Mega's "technical" support only answer with canned responses.
